// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Planora.Infrastructure.Data;

#nullable disable

namespace Planora.Infrastructure.Migrations
{
  [DbContext(typeof(ApplicationDbContext))]
  [Migration("20260427193200_AddBacklogItemDueDateAndStoryPoints")]
  partial class AddBacklogItemDueDateAndStoryPoints
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
  }
}